/* eslint-disable */
export const categories = [
    {
        id: 'b899ec30-b85a-40ab-bb1f-18a596d5c6de',
        parentId: null,
        name: 'Mens',
        slug: 'mens',
    },
    {
        id: '07986d93-d4eb-4de1-9448-2538407f7254',
        parentId: null,
        name: 'Ladies',
        slug: 'ladies',
    },
    {
        id: 'ad12aa94-3863-47f8-acab-a638ef02a3e9',
        parentId: null,
        name: 'Unisex',
        slug: 'unisex',
    },
];
export const brands = [
    {
        id: 'e1789f32-9475-43e7-9256-451d2e3a2282',
        name: 'Benton',
        slug: 'benton',
    },
    {
        id: '61d52c2a-8947-4a2c-8c35-f36baef45b96',
        name: 'Capmia',
        slug: 'capmia',
    },
    {
        id: 'f9987124-7ada-4b93-bef7-35280b3ddbd7',
        name: 'Lara',
        slug: 'lara',
    },
    {
        id: '5913ee46-a497-41db-a118-ee506011529f',
        name: 'Premera',
        slug: 'premera',
    },
    {
        id: '2c4d98d8-f334-4125-9596-862515f5526b',
        name: 'Zeon',
        slug: 'zeon',
    },
];
export const tags = [
    {
        id: '167190fa-51b4-45fc-a742-8ce1b33d24ea',
        title: 'mens',
    },
    {
        id: '3baea410-a7d6-4916-b79a-bdce50c37f95',
        title: 'ladies',
    },
    {
        id: '8ec8f60d-552f-4216-9f11-462b95b1d306',
        title: 'unisex',
    },
    {
        id: '8837b93f-388b-43cc-851d-4ca8f23f3a61',
        title: '44mm',
    },
    {
        id: '8f868ddb-d4a2-461d-bc3b-d7c8668687c3',
        title: '40mm',
    },
    {
        id: '2300ac48-f268-466a-b765-8b878b6e14a7',
        title: '5 ATM',
    },
    {
        id: '0b11b742-3125-4d75-9a6f-84af7fde1969',
        title: '10 ATM',
    },
    {
        id: '0fc39efd-f640-41f8-95a5-3f1d749df200',
        title: 'automatic',
    },
    {
        id: '7d6dd47e-7472-4f8b-93d4-46c114c44533',
        title: 'chronograph',
    },
    {
        id: 'b1286f3a-e2d0-4237-882b-f0efc0819ec3',
        title: 'watch',
    },
];
export const vendors = [
    {
        id: '987dd10a-43b1-49f9-bfd9-05bb2dbc7029',
        name: 'Evel',
        slug: 'evel',
    },
    {
        id: '998b0c07-abfd-4ba3-8de1-7563ef3c4d57',
        name: 'Mivon',
        slug: 'mivon',
    },
    {
        id: '05ebb527-d733-46a9-acfb-a4e4ec960024',
        name: 'Neogen',
        slug: 'neogen',
    },
];
export const products = [
    {
        id: "1",
        MeningitisCertificationNotExist: "Fugiat sit alias nes",
        MeningitisVaccinaiton: "Proident voluptatem",
        airline: "Air India",
        dateTime: "2024-05-17T00:00:00.000+05:00",
        expireMeningitisCertifate: "Suscipit qui dolor a",
        flightNo: "347",
        from: "islamabad",
        lodge: "lounge 1",
        nationality: "Pakistani",
        noOfPassenger: "Quia consequatur Op",
        pVBeforeArrival: "Ab velit officiis un",
        period: "period 2",
        portPolioVaccination: "Veritatis iste optio",
        portPreventionTreatment: "Architecto sunt nis",
        tripType: "hajj",
        yellowFeverCerNonComplaint: "Quia ea quod veniam",
        yellowFeverCertification: "Aliqua Perspiciatis",
        yellowFeverRecord: "Impedit labore aut"
      },
      {
        id: "2",
        MeningitisCertificationNotExist: "Voluptatum sapiente",
        MeningitisVaccinaiton: "Adipisci excepteur",
        airline: "Emirates",
        dateTime: "2024-06-18T00:00:00.000+05:00",
        expireMeningitisCertifate: "Doloribus omnis assumenda",
        flightNo: "448",
        from: "islamabad",
        lodge: "lounge 2",
        nationality: "Indian",
        noOfPassenger: "Aliquam dignissimos",
        pVBeforeArrival: "Provident nostrum et",
        period: "period 3",
        portPolioVaccination: "Consectetur adipisci",
        portPreventionTreatment: "Molestias officia aut",
        tripType: "ummrah",
        yellowFeverCerNonComplaint: "Consequuntur magni",
        yellowFeverCertification: "Repellendus dolor",
        yellowFeverRecord: "Culpa exercitationem"
      },
      {
        id: "3",
        MeningitisCertificationNotExist: "Iusto pariatur qui",
        MeningitisVaccinaiton: "Commodi autem",
        airline: "Qatar Airways",
        dateTime: "2024-07-19T00:00:00.000+05:00",
        expireMeningitisCertifate: "Inventore veritatis",
        flightNo: "549",
        from: "from 6",
        lodge: "lounge 3",
        nationality: "American",
        noOfPassenger: "Tempora temporibus",
        pVBeforeArrival: "Voluptas molestiae",
        period: "period 4",
        portPolioVaccination: "Assumenda laborum",
        portPreventionTreatment: "Explicabo dolorem",
        tripType: "ummrah",
        yellowFeverCerNonComplaint: "Odio libero",
        yellowFeverCertification: "Quasi veritatis",
        yellowFeverRecord: "Exercitationem est"
      },
      {
        id: "4",
        MeningitisCertificationNotExist: "Consectetur repellat",
        MeningitisVaccinaiton: "Labore eius",
        airline: "British Airways",
        dateTime: "2024-08-20T00:00:00.000+05:00",
        expireMeningitisCertifate: "Rerum fugiat",
        flightNo: "650",
        from: "Karachi ",
        lodge: "lounge 4",
        nationality: "British",
        noOfPassenger: "Sint quos",
        pVBeforeArrival: "Quibusdam magni",
        period: "period 5",
        portPolioVaccination: "Architecto minus",
        portPreventionTreatment: "Debitis iste",
        tripType: "ummrah",
        yellowFeverCerNonComplaint: "Autem quibusdam",
        yellowFeverCertification: "Possimus eaque",
        yellowFeverRecord: "Voluptatibus nisi"
      },
      {
        id: "5",
        MeningitisCertificationNotExist: "Molestiae reiciendis",
        MeningitisVaccinaiton: "Quasi ratione",
        airline: "Lufthansa",
        dateTime: "2024-09-21T00:00:00.000+05:00",
        expireMeningitisCertifate: "Adipisci quae",
        flightNo: "751",
        from: "Karachi ",
        lodge: "lounge 5",
        nationality: "German",
        noOfPassenger: "Excepturi dolores",
        pVBeforeArrival: "Exercitationem quo",
        period: "period 6",
        portPolioVaccination: "Voluptas blanditiis",
        portPreventionTreatment: "Soluta rerum",
        tripType: "Trip Type 6",
        yellowFeverCerNonComplaint: "Enim quisquam",
        yellowFeverCertification: "Cupiditate aperiam",
        yellowFeverRecord: "Dicta aliquid"
      },
      {
        id: "6",
        MeningitisCertificationNotExist: "Numquam esse",
        MeningitisVaccinaiton: "Praesentium itaque",
        airline: "Singapore Airlines",
        dateTime: "2024-10-22T00:00:00.000+05:00",
        expireMeningitisCertifate: "Vel omnis",
        flightNo: "852",
        from: "Karachi ",
        lodge: "lounge 6",
        nationality: "Singaporean",
        noOfPassenger: "Repellendus est",
        pVBeforeArrival: "Ratione repellat",
        period: "period 7",
        portPolioVaccination: "Pariatur in",
        portPreventionTreatment: "Atque explicabo",
        tripType: "Trip Type 7",
        yellowFeverCerNonComplaint: "Quisquam alias",
        yellowFeverCertification: "Voluptates natus",
        yellowFeverRecord: "Adipisci ullam"
      },
      {
        id: "7",
        MeningitisCertificationNotExist: "Doloribus accusamus",
        MeningitisVaccinaiton: "Earum illum",
        airline: "Cathay Pacific",
        dateTime: "2024-11-23T00:00:00.000+05:00",
        expireMeningitisCertifate: "Sunt aut",
        flightNo: "953",
        from: "Karachi ",
        lodge: "lounge 7",
        nationality: "Chinese",
        noOfPassenger: "Ipsam dolorum",
        pVBeforeArrival: "Harum dolor",
        period: "period 8",
        portPolioVaccination: "Quibusdam mollitia",
        portPreventionTreatment: "Reprehenderit nihil",
        tripType: "Trip Type 8",
        yellowFeverCerNonComplaint: "Exercitationem nulla",
        yellowFeverCertification: "Debitis aut",
        yellowFeverRecord: "Illum expedita"
      },
      {
        id: "8",
        MeningitisCertificationNotExist: "Iure tempora",
        MeningitisVaccinaiton: "Veritatis omnis",
        airline: "Turkish Airlines",
        dateTime: "2024-12-24T00:00:00.000+05:00",
        expireMeningitisCertifate: "Accusamus voluptate",
        flightNo: "1054",
        from: "islamabad1",
        lodge: "lounge 8",
        nationality: "Turkish",
        noOfPassenger: "Est explicabo",
        pVBeforeArrival: "Corrupti beatae",
        period: "period 9",
        portPolioVaccination: "Quo eos",
        portPreventionTreatment: "Dolores itaque",
        tripType: "hajj",
        yellowFeverCerNonComplaint: "Mollitia veniam",
        yellowFeverCertification: "Libero quod",
        yellowFeverRecord: "Aperiam maxime"
      },
      {
        id: "9",
        MeningitisCertificationNotExist: "Veniam corporis",
        MeningitisVaccinaiton: "Ipsa facere",
        airline: "Delta",
        dateTime: "2025-01-25T00:00:00.000+05:00",
        expireMeningitisCertifate: "Nostrum dignissimos",
        flightNo: "1155",
        from: "islamabad2",
        lodge: "lounge 9",
        nationality: "American",
        noOfPassenger: "Minima dolorem",
        pVBeforeArrival: "Repellat quaerat",
        period: "period 10",
        portPolioVaccination: "Suscipit incidunt",
        portPreventionTreatment: "Laudantium rerum",
        tripType: "hajj",
        yellowFeverCerNonComplaint: "Numquam eveniet",
        yellowFeverCertification: "Corporis nulla",
        yellowFeverRecord: "Inventore iure"
      },  
];